"""add document chunks

Revision ID: 0fff19349b26
Revises: 7413a6b63f2a
Create Date: 2026-09-24 11:27:12.446574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# pyrefly: ignore [missing-import]
import pgvector


# revision identifiers, used by Alembic.
revision: str = '0fff19349b26'
down_revision: Union[str, None] = '7413a6b63f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('source_section', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
