"""create transactions table

Revision ID: 32793f352c23
Revises: 5ae3668cccc8
Create Date: 2026-09-19 01:39:01.333049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32793f352c23'
down_revision: Union[str, None] = '5ae3668cccc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('txn_type', sa.String(length=10), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('classification_method', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_user_dedupe', 'transactions', ['user_id', 'dedupe_hash'], unique=True)
    op.create_index('ix_transactions_user_id', 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_id', table_name='transactions')
    op.drop_index('ix_transactions_user_dedupe', table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
