"""add fraud scans

Revision ID: 696d510eebc7
Revises: 0f11384952db
Create Date: 2026-09-25 16:37:17.145552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '696d510eebc7'
down_revision: Union[str, None] = '0f11384952db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('input_type', sa.String(length=30), nullable=False),
    sa.Column('raw_input_text', sa.Text(), nullable=False),
    sa.Column('detected_signals', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('scam_category', sa.String(length=100), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fraud_scans')
    # ### end Alembic commands ###
