"""add credit scenarios

Revision ID: 6ac5e5fb87ec
Revises: dd9feaae3090
Create Date: 2026-09-23 09:39:11.994438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac5e5fb87ec'
down_revision: Union[str, None] = 'dd9feaae3090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('proposed_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('annual_interest_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('snapshot_monthly_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_existing_emi', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('snapshot_monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_emi', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_repayment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_interest', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('resulting_dti', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('remaining_cash_flow', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_scenarios')
    # ### end Alembic commands ###
