"""add schemes

Revision ID: 7413a6b63f2a
Revises: 6ac5e5fb87ec
Create Date: 2026-09-23 19:57:01.393991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7413a6b63f2a'
down_revision: Union[str, None] = '6ac5e5fb87ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheme_name', sa.String(length=500), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('states', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('target_groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('occupations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('education_levels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('business_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('min_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=False),
    sa.Column('eligibility_conditions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('required_documents', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('application_process', sa.Text(), nullable=True),
    sa.Column('official_url', sa.String(length=1000), nullable=False),
    sa.Column('department', sa.String(length=500), nullable=False),
    sa.Column('source_document', sa.String(length=500), nullable=True),
    sa.Column('last_verified_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schemes')
    # ### end Alembic commands ###
